version: '3.0'

services:

  ethicaltree-web:
    container_name: ethicaltree-web
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    ports:
      - 3002:80
    working_dir: /app
    command: ash -c "PORT=80 HOST=0.0.0.0 npm start"
    volumes:
      - .:/app
      - /app/node_modules

  ethicaltree-proxy:
    container_name: ethicaltree-proxy
    image: nginx
    depends_on:
      - ethicaltree-web
    ports:
      - 3003:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    external:
      name: ethicaltree

