version: '3'

services:
  web:
    image: applepicke/ethicaltree-web
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - .:/app
    command: bash -c "npm install && npm start"

  api:
    depends_on:
      - mysql
    image: applepicke/ethicaltree-api
    volumes:
      - ../ethicaltree-api:/app
    ports:
      - '3001:3001'
    expose:
      - '3001'
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3001 -b '0.0.0.0'"
    stdin_open: true
    tty: true

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ethicaltree
      - MYSQL_USER=root
    volumes:
      - ./data:/var/lib/mysql

