version: '3.0'

services:

  ethicaltree-web:
    container_name: ethicaltree-web
    image: nginx
    ports:
      - 3002:80
    volumes:
      - ./build:/usr/share/nginx/html:ro

  ethicaltree-proxy:
    container_name: ethicaltree-proxy
    image: nginx
    depends_on:
      - ethicaltree-web
    ports:
      - 3003:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    external:
      name: ethicaltree

