FROM node:9.10-alpine

ENV HOME /app
ENV PATH="./node_modules/.bin:${PATH}"

ADD ./package.json /app/
ADD ./package-lock.json /app/

RUN apk --update add --virtual build-dependencies build-base linux-headers && \
  cd /app && \
  npm install

WORKDIR /app

CMD ["npm", "start"]
