export const EXPORT_FIELDS = {
  listings: {
    id: 'ID',
    description: 'Description',
    slug: 'Slug',
    title: 'Title',
    plan_info: 'Plan Information',
    visibility: 'Visibilty',
    claim: 'Claim Info',
    website: 'Website',
    phone_number: 'Phone Number',
    tags: 'Tags',
    ethicalities: 'Ethicalities',
    latlng: 'Lat,Lng',
    address: 'Address',
    city: 'City',
    images: 'Images',
    menu_images: 'Menu Images',
    facebook_uri: 'Facebook URI',
    operating_hours: 'Operating Hours',
  },
  seo_paths: {
    path: 'Path',
    title: 'Title',
    description: 'Description',
    header: 'Header',
  },
}

export const IMPORT_FIELDS = {
  listings: {
    description: 'Description',
    visibility: 'Visibilty',
    title: 'Title',
    website: 'Website',
    phone_number: 'Phone Number',
    tags: 'Tags',
    ethicalities: 'Ethicalities',
    latlng: 'Lat,Lng',
    address: 'Address',
    facebook_hours: 'Facebook Hours',
    google_hours: 'Google Hours',
    images: 'Images',
    menu_images: 'Menu Images',
    facebook_uri: 'Facebook URI',
  },
  seo_paths: {
    path: 'Path',
    title: 'Title',
    description: 'Description',
    header: 'Header',
  },
}
